sudo go get -u github.com/kisielk/errcheck 
sudo go get -u github.com/davidrjenni/reftools/cmd/fillstruct 
sudo go get -u github.com/nsf/gocode 
sudo go get -u github.com/rogpeppe/godef 
sudo go get -u github.com/zmb3/gogetdoc 
sudo go get -u golang.org/x/tools/cmd/goimports 
sudo go get -u github.com/golang/lint/golint 
sudo go get -u github.com/alecthomas/gometalinter 
sudo go get -u github.com/fatih/gomodifytags 
sudo go get -u golang.org/x/tools/cmd/gorename 
sudo go get -u github.com/jstemmer/gotags 
sudo go get -u golang.org/x/tools/cmd/guru 
sudo go get -u github.com/josharian/impl 
sudo go get -u github.com/dominikh/go-tools/cmd/keyify 
sudo go get -u github.com/fatih/motion
